### PR TITLE
Added missing spaCy requirement to README

### PR DESCRIPTION
**Pull request by StefPac**
This PR addresses issue #3

### CODE REVIEW

**Comment by danielhers** [comment]
Thanks! [`setup.py`](https://github.com/danielhers/tupa/blob/master/setup.py#L40) tries to do this automatically though. If it fails, that's another issue.

**Comment by StefPac** [comment]
I used the `pip install tupa` branch of the instructions, so I didn't run `setup.py`.

**Comment by danielhers** [comment]
Well, `pip` still runs `setup.py` behind the scenes, so it should still do it. I'll try to see why it might not work and give a better error message with information on how to download the model manually if it failed. Do you have any logs perhaps?

**Comment by StefPac** [comment]
These are the spaCy relevant bits:

```
Collecting spacy>=1.9.0 (from tupa)
  Downloading spacy-1.9.0.tar.gz (3.4MB)
 100% |████████████████████████████████| 3.4MB 294kB/s 
[...]
Running setup.py bdist_wheel for spacy ... 
done
  Stored in directory: /home/spacific/.cache/pip/wheels/8c/a9/96/dba5bf6fdd55d8c04e9ffb1b6244137c36e8b33e03d3e66a9a
```

**Comment by danielhers** [comment]
Thanks. If this happens after running `setup.py` for tupa, then this explains it. I'll try running it myself and see.

**Comment by danielhers** [comment]
The cause for the problem is that TUPA version 1.1.1 from pip uses a wheel install, which actually doesn't run `setup.py` and never gets the spaCy model. I think the solution will just be to keep only an sdist (.tar.gz) on PyPI, but currently there's a problem with the sdist for 1.1.1 (it doesn't have `requirements.txt`) so I need to fix this.
Thanks for catching this.

**Pull request closed without merging**
